const getters = {
  userid: state => state.userid,
  avatar: state => state.avatar,
  auth: state => state.auth,
  inviteCode: state => state.inviteCode,
  courseid: state => state.courseid,
  classroomid: state => state.classroomid,
  coursename: state => state.coursename,
  socket: state => state.socket,
  lessonid: state => state.lessonid,
  presentationid: state => state.presentationid,
  isBrandNewPpt: state => state.isBrandNewPpt,
  errType: state => state.errType,

  current: state => state.current,
  total: state => state.total,
  pptData: state => state.pptData,
  finishedQuizList: state => state.finishedQuizList,
  participantList: state => state.participantList,
  newtougao: state => state.newtougao,
  isPPTVersionAboveOne: state => state.isPPTVersionAboveOne,
  
  qrcodeStatus: state => state.qrcodeStatus,
  isDanmuOpen: state => state.isDanmuOpen,
  newdoubt: state => state.newdoubt,
  newtougao: state => state.newtougao,
  idIndexMap: state => state.idIndexMap,
  postingDanmuid: state => state.postingDanmuid,
  postingSubmissionid: state => state.postingSubmissionid,
  postingSubmissionSent: state => state.postingSubmissionSent,
  postingSubjectiveid: state => state.postingSubjectiveid,
  postingSubjectiveSent: state => state.postingSubjectiveSent,

  isMsgMaskHidden: state => state.isMsgMaskHidden,
  isToastCtrlMaskHidden: state => state.isToastCtrlMaskHidden,
  isInitiativeCtrlMaskHidden: state => state.isInitiativeCtrlMaskHidden,
  isEnterEnded: state => state.isEnterEnded,
  isPubCheckProblemBtnHidden: state => state.isPubCheckProblemBtnHidden,
  isProblemPublished: state => state.isProblemPublished,

  msgMaskTpl: state => state.msgMaskTpl,
  toastCtrlMaskTpl: state => state.toastCtrlMaskTpl,
  initiativeCtrlMaskTpl: state => state.initiativeCtrlMaskTpl,
};
export default getters
