ARG CI_PROJECT_PATH
ARG CI_COMMIT_REF_NAME
ARG CI_COMMIT_SHORT_SHA
ARG CI_COMMIT_TAG
FROM ${DOCKER_REGISTRY_XTNG}${CI_PROJECT_PATH}:${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA} as dist

FROM ${DOCKER_REGISTRY_XTNG}ops/upload_oss:v0.0.1
ARG CI_COMMIT_REF_NAME
ARG CI_COMMIT_SHORT_SHA
ARG CI_COMMIT_TAG
COPY --from=dist /export/remote /export/remote
RUN if [ -z "$CI_COMMIT_TAG" ]; then ossutil64 cp -r /export/remote oss://fe-static-yuketang/fe/static/lesson/0.0.0-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}; else ossutil64 cp -r /export/remote oss://fe-static-yuketang/fe/static/lesson/${CI_COMMIT_TAG}; fi
